require 'mybase'
--require 'myplugins'
require 'mybufferline'
require 'myluatree'
require 'mytreesitter'
require 'myfzf'
require 'mylsp'
require 'mynullls'
require 'mycmp'
require 'mylualine'
require 'myindentline'
--require 'myshade'
require 'mytokyonight'
vim.o.guifont = "JetBrainsMono Nerd Font:h11"
