#!/bin/bash

server=$HOME/.jdtls

java \
    -Declipse.application=org.eclipse.jdt.ls.core.id1 \
    -Dosgi.bundles.defaultStartLevel=4 \
    -Declipse.product=org.eclipse.jdt.ls.core.product \
    -Xms1G \
    -Xmx2G \
    -jar $server/plugins/org.eclipse.equinox.launcher_1.*.jar \
    -configuration $server/config_linux/ \
    -data $HOME/.cache/jdtls/ \
    --add-modules=ALL-SYSTEM \
    --add-opens java.base/java.util=ALL-UNNAMED \
    --add-opens java.base/java.lang=ALL-UNNAMED 
